# Copy required directories (Main.py sits at same level as src) - TODO: This needs some work and testing

COPY docs container/docs
COPY app container/app
COPY data container/data
COPY settings.toml container/

# Set the working directory

WORKDIR /container

# Run app

ENTRYPOINT ["streamlit", "run", "app/Main.py", "--server.port=8080", "--server.address=0.0.0.0"]

# See https://discuss.streamlit.io/t/deploying-streamlit-on-gcp-cloud-run-problem-when-using-new-multipage-app-feature/26316/3
