# See: https://cloud.google.com/run/docs/quickstarts/build-and-deploy/deploy-python-service

FROM python:{{PYTHON_VERSION}}-slim-bullseye
RUN apt-get update && apt-get install -y git

# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

# Environment variables (set from `.secrets_env.toml`)