# See https://stackoverflow.com/questions/68673221/warning-running-pip-as-the-root-user
# for enhancements to Dockerfile e.g. not running as root & in venv

FROM python:3.10-slim-bullseye
RUN apt-get update && apt-get install -y git
