# Copy required directories (Main.py sits at same level as src) - TODO: This needs some work and testing

COPY docs app/docs
COPY app app/app
COPY data app/data
COPY settings.toml app/

# Set the working directory

WORKDIR /app

# Run app

ENTRYPOINT ["streamlit", "run", "{{STREAMLIT_RUN_PY}}", "--server.port={{PORT}}", "--server.address=0.0.0.0"]

# See https://discuss.streamlit.io/t/deploying-streamlit-on-gcp-cloud-run-problem-when-using-new-multipage-app-feature/26316/3
